### ISSUE TITLE
Authentication frontend configuration

### ISSUE THREAD

**Issue by havenousername** [AbduAliAndrei/fullstack-renting-application#25]
- Updating `/login` and creating `/register` pages
- Login and Registration `session` find and use with  endpoint `api/auth/check` (should be the first request private routes) 
```
{
  sessionCookie = {session} 
 }
```
- UI / UX `/login` and `/register`

**Comment by AlexHelmutSonntag** [comment]
Closing issue as per discussion with @havenousername  and @Abdulla-Alkhulaqui
