### ISSUE TITLE
Login/Register Page UI/UX together with backend connection

### ISSUE THREAD

**Issue by havenousername** [AbduAliAndrei/fullstack-renting-application#32]
- Login UI
- Register UI
- Backend fetch user and overall way of correct connection

**Comment by havenousername** [comment]
@Abdulla-Alkhulaqui  Please try to use MUI as much as possible here. A good approach would be to use `Hook API` for it. Try to get acquainted to it, here is the link: (MUI Hook API )[https://mui.com/styles/basics/#hook-api]

**Comment by AlexHelmutSonntag** [comment]
- [ ] After Registering/Logging in, user should not see the header with the "login" or "signup" buttons, they should see something like a user icon where it takes them to their profile. The sign out button should be right next to it. we will make a figma design for this today after the other topics we need to work on. @Abdulla-Alkhulaqui @havenousername

**Comment by havenousername** [comment]
done in Front-End branhc
