### ISSUE TITLE
Creating new middlewares for controlling security layers.

### ISSUE THREAD

**Issue by AlexHelmutSonntag** [AbduAliAndrei/fullstack-renting-application#64]
- [x] Create tenants only middleware to control routes available only for tenants  
- [x] Create landlords  middleware to control routes available only for landlords  
- [x] Create special middleware for admins + moderators(Moderators to be implemented in the future)
- [x] Create middleware to manage access for users (Updating/Deleting own listings for tenants + updating/deleting blogposts for users)

**Comment by havenousername** [comment]
@AlexHelmutSonntag everything is done at #65 according to requirements of update and view functionality of future routes
