### ISSUE TITLE
Add ci/cd pipelines for some package.json scripts

### ISSUE THREAD

**Issue by havenousername** [AbduAliAndrei/fullstack-renting-application#68]
Please add this lines to pipeline on ci/cd

- https://github.com/AbduAliAndrei/fullstack-renting-application/blob/9d7317211e3ebf29c6a45a550c36901163ee3795/package.json#L6
- https://github.com/AbduAliAndrei/fullstack-renting-application/blob/9d7317211e3ebf29c6a45a550c36901163ee3795/package.json#L12
- https://github.com/AbduAliAndrei/fullstack-renting-application/blob/9d7317211e3ebf29c6a45a550c36901163ee3795/package.json#L13

**Comment by AlexHelmutSonntag** [comment]
Issue resolved.
