### ISSUE TITLE
Create frontend Offers final view

### ISSUE THREAD

**Issue by havenousername** [AbduAliAndrei/fullstack-renting-application#72]
- [ ] Offers Details Page reactive component
  - [ ] Offers Details can be edited with Landlord
  - [ ] Offers Creation page
  - [ ] Offers Filtering page final design

**Comment by havenousername** [comment]
@Abdulla-Alkhulaqui Is this issue under process?

**Comment by Abdulla-Alkhulaqui** [comment]
Issue resolved
